/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.util.Scanner;

/**
 *
 * @author Shashika
 */
public class mechanicalCal extends javax.swing.JFrame {

    /**
     * Creates new form mechanicalCal
     */
    public mechanicalCal() {
        initComponents();
    }
    
    double d,t,u,v,a, answer;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        display = new javax.swing.JTextField();
        lastVelocity = new javax.swing.JButton();
        acceleration = new javax.swing.JButton();
        time = new javax.swing.JButton();
        startVelocity = new javax.swing.JButton();
        distance = new javax.swing.JButton();
        lastVelocityresult = new javax.swing.JButton();
        accelerationresult = new javax.swing.JButton();
        timeresult = new javax.swing.JButton();
        startVelocityresult = new javax.swing.JButton();
        distanceresult = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        display.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });
        getContentPane().add(display, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 490, 80));

        lastVelocity.setText("V");
        lastVelocity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastVelocityActionPerformed(evt);
            }
        });
        getContentPane().add(lastVelocity, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 90, 70));

        acceleration.setText("a");
        acceleration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accelerationActionPerformed(evt);
            }
        });
        getContentPane().add(acceleration, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 90, 70));

        time.setText("T");
        time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeActionPerformed(evt);
            }
        });
        getContentPane().add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 90, 70));

        startVelocity.setText("U");
        startVelocity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startVelocityActionPerformed(evt);
            }
        });
        getContentPane().add(startVelocity, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 90, 70));

        distance.setText("D");
        distance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distanceActionPerformed(evt);
            }
        });
        getContentPane().add(distance, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 90, 70));

        lastVelocityresult.setText("V");
        getContentPane().add(lastVelocityresult, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 90, 70));

        accelerationresult.setText("a");
        accelerationresult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accelerationresultActionPerformed(evt);
            }
        });
        getContentPane().add(accelerationresult, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 90, 70));

        timeresult.setText("T");
        getContentPane().add(timeresult, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 90, 70));

        startVelocityresult.setText("U");
        getContentPane().add(startVelocityresult, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 90, 70));

        distanceresult.setText("D");
        distanceresult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distanceresultActionPerformed(evt);
            }
        });
        getContentPane().add(distanceresult, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 90, 70));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 80, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
       
    }//GEN-LAST:event_displayActionPerformed

    private void distanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distanceActionPerformed
        d = Double.parseDouble(display.getText());
        display.setText("");
    }//GEN-LAST:event_distanceActionPerformed

    private void accelerationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accelerationActionPerformed
        a = Double.parseDouble(display.getText());
        display.setText("");
    }//GEN-LAST:event_accelerationActionPerformed

    private void accelerationresultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accelerationresultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accelerationresultActionPerformed

    private void distanceresultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distanceresultActionPerformed
        if(u != 0 && t != 0 && a != 0){
            answer = (u*t)+(0.5*a*t*t);
          display.setText(String.valueOf(answer));
        } else if(u != 0 && v != 0 && t != 0){
            answer = (u+v)*0.5*t;
            display.setText(String.valueOf(answer));}
        else if (v != 0 && u != 0 && a != 0 ){
               answer = (v*v - u*u)/2*a;
                display.setText(String.valueOf(answer));}
    }//GEN-LAST:event_distanceresultActionPerformed

    private void timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeActionPerformed
        t = Double.parseDouble(display.getText());
        display.setText("");
    }//GEN-LAST:event_timeActionPerformed

    private void startVelocityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startVelocityActionPerformed
        u = Double.parseDouble(display.getText());
        display.setText("");
    }//GEN-LAST:event_startVelocityActionPerformed

    private void lastVelocityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastVelocityActionPerformed
        v = Double.parseDouble(display.getText());
        display.setText("");
    }//GEN-LAST:event_lastVelocityActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        a = 0;
        v = 0;
        u = 0;
        d = 0;
        t = 0;
        display.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mechanicalCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mechanicalCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mechanicalCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mechanicalCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mechanicalCal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceleration;
    private javax.swing.JButton accelerationresult;
    private javax.swing.JTextField display;
    private javax.swing.JButton distance;
    private javax.swing.JButton distanceresult;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton lastVelocity;
    private javax.swing.JButton lastVelocityresult;
    private javax.swing.JButton startVelocity;
    private javax.swing.JButton startVelocityresult;
    private javax.swing.JButton time;
    private javax.swing.JButton timeresult;
    // End of variables declaration//GEN-END:variables
}
